Add sweep and edit config for CI
ministry-of-silly-code/examples pull request #1
Opened 2021-07-31 17:45 UTC by d3sm0

2021-08-17 18:49 UTC, manuel-delverme requested changes

2021-08-17 18:49 UTC, manuel-delverme commented on config.py
> +if os.environ.get('SWEEP', ""):
no need for if

2021-08-18 01:27 UTC, d3sm0 commented on config.py
> +if os.environ.get('SWEEP', ""):
...sry

2021-08-18 01:27 UTC, d3sm0 commented
read to merge.

2021-09-04 20:26 UTC, manuel-delverme approved these changes

2021-09-06 00:00 UTC, merged